"""Agent planning layer for Sephirot workflows."""

from __future__ import annotations

from typing import Any

from .validation import ValidationIssue, validate_spec


ROLE_DESCRIPTIONS = {
    "Framework Steward": "Protect the canonical schema, version, and validation contract.",
    "Malkuth Witness": "Ground the current state in concrete evidence.",
    "Kether Architect": "Clarify the target state and success condition.",
    "Sephira Mapper": "Fill the 10 focus values with domain-specific ontology content.",
    "Path Auditor": "Make the 22 Competency Question paths answerable.",
    "Qliphoth Red Team": "Expose mirror risks, distortions, and failure modes.",
    "Graph Scribe": "Build, visualize, and export the final graph artifacts.",
}


def _role_for_key(key: str) -> str:
    if key.startswith("malkuth."):
        return "Malkuth Witness"
    if key.startswith("kether."):
        return "Kether Architect"
    if "qliphoth" in key:
        return "Qliphoth Red Team"
    if key.startswith("sephira."):
        return "Sephira Mapper"
    if key.startswith("paths."):
        return "Path Auditor"
    return "Framework Steward"


def _task(role: str, action: str, evidence: str, key: str = "") -> dict[str, str]:
    return {
        "role": role,
        "description": ROLE_DESCRIPTIONS[role],
        "key": key,
        "action": action,
        "evidence_required": evidence,
    }


def _issue_task(issue: ValidationIssue) -> dict[str, str]:
    return _task(
        "Framework Steward",
        f"Repair {issue.key}: {issue.message}",
        "A clean validation report with no structural errors.",
        issue.key,
    )


def agent_plan(spec: dict[str, Any]) -> dict[str, Any]:
    """Create a Hermes/Codex/Claude-style work plan from a seed spec."""

    report = validate_spec(spec)
    tasks: list[dict[str, str]] = []

    for issue in report.errors:
        tasks.append(_issue_task(issue))

    for item in report.next_questions:
        key = str(item["key"])
        role = _role_for_key(key)
        tasks.append(
            _task(
                role,
                str(item["question"]),
                "A seed spec field update with concrete text and at least one evidence artifact where applicable.",
                key,
            )
        )

    if report.ok:
        tasks.extend(
            [
                _task(
                    "Graph Scribe",
                    "Build the dual Sephirot/Qliphoth graph.",
                    "`sephirot.graph.json` generated by `python3 -m sephirot.cli build`.",
                ),
                _task(
                    "Graph Scribe",
                    "Render the graph for inspection.",
                    "SVG, HTML, or Mermaid artifact generated by `python3 -m sephirot.cli visualize`.",
                ),
                _task(
                    "Graph Scribe",
                    "Export the graph to Neo4j Cypher when graph database loading is needed.",
                    "`sephirot.cypher` generated by `python3 -m sephirot.cli export-neo4j`.",
                ),
            ]
        )

    return {
        "schema_version": "0.1",
        "status": "ready-to-build" if report.ok else "needs-refinement",
        "ambiguity": report.ambiguity,
        "threshold": report.threshold,
        "roles": [
            {"role": role, "description": description}
            for role, description in ROLE_DESCRIPTIONS.items()
        ],
        "tasks": tasks,
    }


def plan_as_markdown(plan: dict[str, Any]) -> str:
    lines = [
        f"# Sephirot Agent Plan: {plan['status']}",
        "",
        f"- Ambiguity: {plan['ambiguity']:.3f}",
        f"- Threshold: {plan['threshold']:.3f}",
        "",
        "## Tasks",
        "",
    ]
    for index, task in enumerate(plan["tasks"], start=1):
        key = f" `{task['key']}`" if task.get("key") else ""
        lines.extend(
            [
                f"{index}. **{task['role']}**{key}",
                f"   - Action: {task['action']}",
                f"   - Evidence: {task['evidence_required']}",
            ]
        )
    if not plan["tasks"]:
        lines.append("No tasks. The seed is already ready.")
    return "\n".join(lines) + "\n"
